n = int(input('Um número: '))
d = (n * 2)
t = (n * 3)
r = (n ** (1/2))
print('O dobro do número {} é {}. \nO triplo do número {} é {}. \nA raiz quadrada do número {} é {:.2f}.'.format(n, d, n, t, n, r))
